### ISSUE TITLE
Frontend erroneously sends `count=true` to non-pool requests

### ISSUE THREAD

**Issue by nidico** [liqd/adhocracy3#1376]
Symptom: Requests with unexpected query parameters may lead to an outdated varnish cache, as the backend sends wrong purge requests.

@joka wrote a workaround in d4e3b689a443fae57e0e6cea35d3e9ffafb9a8d9, which basically purges "too much", but avoids the symptom.

Possible solution: in `Listing ... $scope.update`, call `getElements` with `warmup` as second parameter. This makes sure, count is only called for containers, which `canWarmup`, i.e. pools. This is a bit confusing, but should work.

**Comment by xi** [comment]
> @joka wrote a workaround in d4e3b68, which basically purges "too much", but avoids the symptom.

I would expect that additional query parameters are ignored by the server because that is the default behavior of traditional apache setups. It might be ok to respond with 400. But we should not ignore the parameters in the application and acknowledge it in the cache.

**Comment by xi** [comment]
After some messing around with frontend code I think that the issue is that we have to much pool specific code in the `Listing` class. It should probably be moved to the adapters. Then again, I am not sure how this should be implemented without doing many similar requests (initial one, one to get the count, one each time we request elements).
