### ISSUE TITLE
migrate ae staging?

### ISSUE THREAD

**Issue by MagdaN** [liqd/adhocracy3#1954]
with https://github.com/liqd/adhocracy3/pull/1948 a field in mercator proposal 2016 was changed but no migration provided. The problem is, that we cannot just delete the database on staging in order to get that working again, because the users and proposals from 2015 are in there. What should we do?

**Comment by pallix** [comment]
So we saw three solutions with @MagdaN 

1) overwrite staging db with a version before proposals from 2016 were created

2) mark current proposal as hidden/delete, thus preventing them from being accessed

3) write a migration script

I'm against 3) because  writing migration script for data that are not in production is losing time for nothing

2) seems hacky.

1 = win?

**Comment by pallix** [comment]
1) was done by @xi, thanks!
