### ISSUE TITLE
No distinction between frontend_url and canonical_url in backend

### ISSUE THREAD

**Issue by xi** [liqd/adhocracy3#2168]
The backend uses the config `adhocracy.frontend_url` for two very different things:
-  Point to a place where adhocracy is **embedded**, e.g. for activation links. This is equivalent to what is called `adhocracy.canonical_url` in the frontend config.
-  Point to the frontend **itself**. This is used in `embed_code.html.mako`.

The second usecase was added only recently in #2083. So all deployed configuration assumes the first usecase. I propose to use `adhocracy.canonical_url` for the first usecase to be consistent with the frontend config and use `adhocracy.frontend_url` for the second.

**Comment by xi** [comment]
Related to #1006

**Comment by joka** [comment]
To make things easier to understand we should use the same config options for the frontend and backend server if possible. This also ease removing the frontend server and add the same functionaltity to the backend server (we already have a prototype for this).

To fix the describe issue I would add 'adhocracy.cannocial_url'  to the backend config and use this instead of 'adhocracy.frontend_url'  (except for embed_code.html.mako). If we remove the frontend_server  later we can remve 'frontend_url'.

**Comment by xi** [comment]
Potential duplicate of #1006
