### ISSUE TITLE
mein.berlin.de: on clicking AddProposalButton, two login links are visible

### ISSUE THREAD

**Issue by der-john** [liqd/adhocracy3#2213]
See https://meinberlin-stage.liqd.net/w/prozesse/altstadt-2016/

**what I did**: Navigate to a process without logging in; click on "add proposal".
**wanted result**: I see https://meinberlin-stage.liqd.net/w/adh/#!login.
**what actually happens**: I see https://meinberlin-stage.liqd.net/w/prozesse/altstadt-2016/#!login - the "wrong login location". This way I actually see two login buttons: one in the CMS and one in a3.

We need to modify the behavior of the AddProposalButtons and/or the frontend routing. I'm not sure in which way.

**Comment by Johnschmidfront** [comment]
I just realised that the double login is only visible on this one site (https://meinberlin-stage.liqd.net/w/prozesse/altstadt-2016/#!login) and not after logging in. Hence it's not high prio, after all.

**Comment by Johnschmidfront** [comment]
I am quite sure the problem is the following:

1. Some time in 2014/15 the login/ register view of A3 was written. It displays the usual header template (or project customizations of), which contains the logo, login and register buttons, and, below, it displays the login/ register form.
2. In Mar 2016, @xi implemented an A3 login button that appears in the meinberlin wagtail CMS - it directs the user to the site https://meinberlin-stage.liqd.net/w/adh/#!login.
3. At the same time (Mar 16), all* A3 processes that get embedded in the meinberlin wagtail CMS use the context `mein.berlin.de`, which means that the usual header template isn't displayed for these processes, because (2) already contains its elements.
4. Problem: The login page is accessed through a part of the A3 frontend routing that's separate of the processes. Thus, it isn't affected by the `mein.berlin.de`context. It displays the usual header according to (1) as it always has.

*except stadtforum, which uses `meinberlin-stadtforum-proposal-detail`.

**Comment by xi** [comment]
Thanks for the great summary!

I am a bit confused about the last two options: Why would you add an AddProposalButton to the login page? Did you mean to say login/register instead of AddProposalButton?

**Comment by Johnschmidfront** [comment]
Sorry that was unclear. I'd want to add a header overwrite such that, in the meinberlin project, the logo and login/ register links are never shown at all. Unfortunately, I'm afraid we need to keep them for old embeds, though. Am I right?

**Comment by der-john** [comment]
Nico as our designer vetoed the **bold and burdensome solution**. @xi and I talked about the **Conservative and unclear solution** so it's quite clear now and will be realized soon.
