### ISSUE TITLE
advocate europe 2015 Journey not working for some proposals

### ISSUE THREAD

**Issue by 2e2a** [liqd/adhocracy3#2221]
For some proposals the journey button is not working, i.e. no new page is loaded/shown.

This seems to be the case only for proposals with broken proposal versions, e.g. "VERSION_0000002_2016-03-17T22%3A26%3A38.573770%2B00%3A00/"

When appending the "@blog" suffix manually in the URL the journey is loading.

**Comment by xi** [comment]
I did some debugging and this is what I found:

 The same issue also exists with comment links of those proposals

#1002 added a hack that redirects old versions to the newest one. This bugreport exposed two issues in the implementation:

1.  The *view* part of the URL is lost in the redirect.
2. URLs are not properly encoded, so that sometimes a redirect is triggered even if it is not required (e.g. `"…/VERSION_0000002_2016-03-17T22:26:38.573770+00:00"` is compared to `"…/VERSION_0000002_2016-03-17T22%3A26%3A38.573770%2B00%3A00"`)

Note that both issues do not only affect `@blog`, but also `@comments`.

The first issue can be reproduced with the following steps:

- create a mercator 2015 proposal and edit it once so you have two versions
- go to comments of first version
- *expected*: get redirected to comments of second version
- *actually*: get redirected to second version

I created a fix for (1) in #2223. I think we do not need to worry about (2) because it is a bit complicated to fix and does not really hurt.
