### ISSUE TITLE
SubstanceD not correctly updated by buildout

### ISSUE THREAD

**Issue by pallix** [liqd/adhocracy3#2276]
Since #2192 is merged we have several times where SubstanceD failed to be updated to the correct new git commit:

- in deployment when using salt
- locally with buildout, when developing.

**Comment by joka** [comment]
Can you elaborate more what is causing trouble?

locally:

the mr.developer buildout extension takes care for git checkouts. The always-checkout
options controls if the checkouts are automaticall updated or not. The default is False. 
We can change it to True or Force (override a dirty checkout).  
The only downside is buildout takes more time to run. 
 
deployment:

bin/ad_make_wheels creates a wheel from the local git checkout,  but it does not handle checkouts of specific
commits or branches. The package name is the version number specified in setup.py, but not the commit or tag (like the output of `git describe --tags`)

ok, boths is causing trouble i see.

**Comment by joka** [comment]
You can see the list of dependencies relying on git checkout here: src/adhocracy_core/sources.cfg

**Comment by pallix** [comment]
@slomo what's your opinion on this?

**Comment by slomo** [comment]
In my opinion there is no specific deployment problem, because ad_make_wheels is supposed to run after buildout. So if buildout would work properly than we are fine.

This issue occurred not only on production but also on several developer machines where I manually fixed it. The repositories weren't dirty. In my opinion the recipe seems to be broken. We can try to find some one with an old installation where the issue still arises and debug a bit.
