### ISSUE TITLE
Do not put session token in local storage

### ISSUE THREAD

**Issue by xi** [liqd/adhocracy3#2299]
This is a security issue: https://www.owasp.org/index.php/HTML5_Security_Cheat_Sheet#Local_Storage

See also #2271

**Comment by slomo** [comment]
So should we switch to http-only cookies instead and disable CORS?

**Comment by joka** [comment]
> So should we switch to http-only cookies instead and disable CORS?

+1  Cookie authentication
according to wasp it is more secure if we are protected against CSRF,  mainly  because  we cannot trust 
3. party javascript and  the browser security concept for local storage / javascript isolation is prune to have bugs. Also it makes SSO with server side rendered application on the same domain more easy.
But its some work:

           -  add login/logout api endpoint 
           -  adapt frontend/backend
           - add CSRF protection

Token Header authencation should still be possible to allow third part access for 3rd part programms, like for meinberlin.  It would prefere to have a special login endpoint for this to have a clear  separation.d

**Comment by xi** [comment]
Duplicate of #2318
