### ISSUE TITLE
Introduce real delete

### ISSUE THREAD

**Issue by slomo** [liqd/adhocracy3#2336]
Currently A3 does support two types of delete:

 * flag as deleted
 * flag as hidden

( see current [documentation](https://github.com/liqd/adhocracy3/blob/d86ca20492273028bee85f652edb52be8ef75303/src/adhocracy_core/docs/deletion.rst) on deletion)

This results in some unexpected behaviour when deleting some special resources, like badge assignments. Once User Marcella has delete an badge assignment, User Lisa can't recreate the same badge assignment. She can't assign the badge again, because it is already assigned. She also can't remove the delete flag from the old assignment because she is neither creator of this assignment nor admin.

**Proposal:**

Change the current "flag as delete" feature into a real delete, using the HTTP `delete` verb.

**Analysis:**

In the frontend this delete is only used in two places:

 - User, Moderator or Inititator deletes a badge assignments
    - mark as deleted functionality is not optimal, reason for the pull-request
 - Creator of a proposal deletes a blog entries in mercator
    - TODO: what happens here if change the semantic of delete

FYI:  There are also three occurrences of hide:
 - Initiator or Moderator clicks "delete" button on a comment
 - Intitator or Moderator click "delete" on a proposal in mercator 2015
 - Intitiator or Moderator clicks "delete" button on a document in Alexanderplatz

As we see the semantic holds so far.

**Questions:**

 - Do we want to allow users in certain conditions to recover deleted Material.
     * We don't want it in any because it might cause problems as with badge assignments
 - If so, could we also use hide in those conditions or do we need a third concept for real deletion?

**Comment by slomo** [comment]
I would personally say we should not have a recoverable delete and a real delete. For the sake of simplicity. In general user won't expect to be stuff  be recoverable, because that is not what web apps tend to offer.

So I would say we replace "mark as deleted" directly with "real delete".

**Comment by slomo** [comment]
Please share your opinions @liqd/write-access-adhocracy-3

**Comment by xi** [comment]
IMHO recovering deleted content for some time (~1h) would be a nice usability feature, but it is not top priority. I guess we could still add that feature later, even if we use the DELETE verb.

There might be legal or poltical constraints though (e.g. being able to justify why a comment was deleted by moderators).

**Comment by xi** [comment]
Related: #1693

**Comment by joka** [comment]
+1  this also simplifies the backend implementation.

I'm unsure for political reasons if we want real delete for comments or better use hide instead.
Did someone talked with the POs about this matter?

**Comment by joka** [comment]
We should consider who and what can be deleted. I guess rates should not be deleted for political reasons.

**Comment by xi** [comment]
I talked to @rukala about political implications. We came up with the following restrictions:

-   For some installations, we need a way to tell what content was created for up to 2 weeks. This can also be in the form of a separate log.
-   If a proposal has sparked a bigger discussion, the creator should not be able to delete the proposal, even though they have edit permissions. Therefore we need a special `delete_resource` permission.

**Comment by joka** [comment]
> For some installations, we need a way to tell what content was created for up to 2 weeks. This can also be in the form of a separate log.

Is it enought to use the existing audit log? (it stores only the name aka database identifier)

**Comment by joka** [comment]
> If a proposal has sparked a bigger discussion, the creator should not be able to delete the proposal, even though they have edit permissions. Therefore we need a special delete_resource permission.

what is the definition of "bigger discussion"?

**Comment by xi** [comment]
> Is it enough to use the existing audit log? (it stores only the name aka database identifier)

We need to keep all information for at least 2 weeks. So either we keep the data in the database after it has been deleted or we include all content in the audit log.

> what is the definition of "bigger discussion"?

Not relevant. This was only to motivate why we need a separate permission for deletion (before it was the same as edit).

**Comment by joka** [comment]
> Is it enough to use the existing audit log? (it stores only the name aka database identifier)
> We need to keep all information for at least 2 weeks. So either we keep the data in the database after it has been deleted or we include all content in the audit log.

What is the use case for this kind of "backup"?
 As i understood this the the Sysadmin  should been able to list deleted resources and its content.

**Comment by xi** [comment]
As said before, it is a legal requirement to store all content for at least 2 weeks. It is not important whether the content is in the database or in an external log or wherever. I just needs to be somewhere. I am not sure what your question is.

**Comment by joka** [comment]
To implement this I need to know Who should be able to see the deleted resources and how should this happen?

**Comment by joka** [comment]
To enrich my question: we have implemented the audit log, but its to complicated to use, so nowbody knows if realy works or if we log usefull stuff.

**Comment by xi** [comment]
We are legally required to have that information and to be able to provide it if necessary. It does not need to be user friendly. So "complicated to use" is not an issue, but we need to be sure that we log the right kind of data.

**Comment by ChristianSi** [comment]
@xi That's hardly a legal requirement, but much more likely a customer requirement, I presume.

But considering that such a requirement exists and is automatically fulfilled as long as the current "mark as deleted" semantics stays in place, I'd conclude that replacing "mark as deleted" by "really delete" is a BAD IDEA.

Why not leave the current "mark as deleted" semantics intact and instead fix the behavior when a user tries to (re)create a "deleted" resource. IMHO the correct semantics for dealing with this use case is as follows:

* Creating a resource whose last existing version has the "deleted" flat is successful whenever the creation of a new resource (without any preceding version) would be successful. In effect, "create" in such a case is autoconverted into "recreate" or "undelete" (but no old content is restored).
* Ownership of the resource is transferred from the original creator to the re-creator.

In effect, this would make "mark as deleted" work like "real delete", except that we don't have to worry about an audit log or similar because the obsolete data is never really deleted, it's merely hidden.

**Comment by xi** [comment]
> @xi That's hardly a legal requirement, but much more likely a customer requirement, I presume.

Sorry. I meant legal as in "we have a contract that requires us to do that"

**Comment by rukala** [comment]
For details on the agreements concerning server logs please contact Nadine K (EUth) and Frede (Advocate Europe).

Thanks!

**Comment by joka** [comment]
Hoi Christian, nice to here you :)

> @xi That's hardly a legal requirement, but much more likely a customer requirement, I presume.
> 
> But considering that such a requirement exists and is automatically fulfilled as long as the current "mark as deleted" semantics stays in place, I'd conclude that replacing "mark as deleted" by "really delete" is a BAD IDEA.
> 
> Why not leave the current "mark as deleted" semantics intact and instead fix the behavior when a user tries to (re)create a "deleted" resource. IMHO the correct semantics for dealing with this use case is as follows:
> 
> Creating a resource whose last existing version has the "deleted" flat is successful whenever the creation of a new resource (without any preceding version) would be successful. In effect, "create" in such a case is autoconverted into "recreate" or "undelete" (but no old content is restored).

To simplify things we made only Simples and Pools/Items deletable, not Versions (they are immutable).

The actual problem we want to solve are badges (Simples) that are deleted and then recreated with the same name. 
Of cause we could solve this with a more sophisticated validation, permission settings. Also
implicit undelete would be possible as a speciifc solution for badges (in general you don't expect your deleted resources to be gone suddenly).
But we need real deletion anyway for some use cases (customer wants real deletion, performance issues due to to many resources) and having 3 kinds of deletion (hidden, deleted, really deleted) without a real need for it is confusing. The requirements to have a "backup" for two weeks came very late, so we did not
really consider this in our decision making.

**Comment by joka** [comment]
Sidenote: we try  not to use Versionables anymore, up to now we stil have no customer use case for it.

**Comment by joka** [comment]
Another issue we should consider, most of our programmers don't like to use adhocracy because its to complicated. So if we have the opertunit to simplify things we should do it.

**Comment by der-john** [comment]
fixed in #2365.
