### ISSUE TITLE
Printing bug for map pins

### ISSUE THREAD

**Issue by Janaba** [liqd/adhocracy3#2382]
When we tried to print out a proposal in map view in the idea-collection, the pin of the proposal was white (instead of blue). The bug already appears in the preview.

lhttps://meinberlin-stage.liqd.net/w/prozesse/tegel/#!r/isek/tegel/

![bildschirmfoto 2016-06-06 um 17 52 33](https://cloud.githubusercontent.com/assets/19778796/15828530/f4cfc5e8-2c0f-11e6-9af9-d3b0e9e8dbf3.png)

**Comment by xi** [comment]
This was a though one!

Actually, it is not related to 51b3490 because markers have the `leaftlet-` prefix.

The actual issue is that browsers automatically optimize stylesheets for printing, i.e. they ignore most backgrounds. There is nothing we can do from our site. Instead, you have to tell your browser to include background-colors in the print dialog:

## chromium on linux

![2016-06-08-114526_1440x900_scrot](https://cloud.githubusercontent.com/assets/202576/15890250/f64b49fa-2d6e-11e6-96a5-48f3e5daa795.png)

## firefox on linux

![2016-06-08-114553_1440x900_scrot](https://cloud.githubusercontent.com/assets/202576/15890256/f99f00ba-2d6e-11e6-9181-394d15ff2dda.png)


Relevant W3C discussion: <https://wiki.csswg.org/ideas/print-backgrounds>. There is also the non-standard CSS attribute [`-webkit-print-color-adjust`](https://developer.mozilla.org/en-US/docs/Web/CSS/-webkit-print-color-adjust) that we could use if absolutely needed.

@JanaGa can you please check whether this fixes your problem?

**Comment by der-john** [comment]
Won't be changed.
