### ISSUE TITLE
locally, badge assignment modal has no badges

### ISSUE THREAD

**Issue by der-john** [liqd/adhocracy3#2535]
**Weird**: This is only an issue on local installations and on the staging server, not on the production server.
**Weird**: This is only an issue for non-god users.

I built meinberlin (or euth) idea collection with badges, logged in as "user" and created a proposal.

The option "Badges" appears in the UI. After I click on it, the regular modal dialog appears. But instead of displaying the four available badges, it displays none.

**Comment by 2e2a** [comment]
This can be reporoduced locally with a fresh database as, a normal user.

The backend permissions seem ok, as the frontend does a successful request to 

`http://localhost:6541/organisation/idea_collection/?content_type=adhocracy_core.sheets.badge.IBadge&depth=4`

and receives the badge paths.

**Comment by xi** [comment]
I reproduced the issue and found that in the options request to `http://localhost:6541/organisation/idea_collection/proposal_0000000/badge_assignments/
`, `POST.request_body[0].data.["adhocracy_core.sheets.badge.IBadgeAssignment"].badge` is an empty list. So I guess the issue is actually in the backend.
