### ISSUE TITLE
Cached images not updated if format size changes

### ISSUE THREAD

**Issue by nidico** [liqd/adhocracy3#773]
If the size of a default format (at the moment `thumbnail` / `detail`) changes, the backend should invalidate cached images and deliver them in the new format.

**Comment by ChristianSi** [comment]
This is not really a bug, since (from the viewpoint of the backend) images sizes can never change, as they are hardwired into the code. If the code is updated that could happen in several ways: format name remains the same but size changes, new format added, old format removed.

"New format added" is automatically handled by the backend, as image sizes are generated on demand. They other two aren't, and I think it would be overly complex to try to handle them in the backend code serving assets.

The better solution should be to write an evolution script that deletes all or some (e.g. just the "thumbnail" view) views  and invoke that script when a format size has been changed or removed.

Alternatively, we could rename the format-specific view to contain the size, e.g. "detail" would become "detail-400x300" or just "400x300". That would lead to new sizes being automatically generated as needed, but the old versions would still stay in the DB and unnecessarily occupy space, so it's not a great solution. And it would also require changes in the frontend whenever the size is changed.

**Comment by xi** [comment]
I agree: this is expected behavior.
